name: StackSpot AI - Agente Sonar - Grupo Kilo

on: 
  push:
    branches: '**'

jobs:
  stackspot-banana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: tj-actions/changed-files@v44
        id: changed-files
      - name: Instalar dependÃªncias
        run: |
          pip install requests
      # - name: Rodar StackSpot Agente Sonar
      #   env:
      #     CLIENT_ID: ${{ secrets.CLIENT_ID }}
      #     CLIENT_KEY: ${{ secrets.CLIENT_KEY }}
      #     CLIENT_REALM: ${{ secrets.CLIENT_REALM }}
      #     QC_SLUG: ${{ secrets.QC_SLUG }}
      #     CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      #   run: python3 .github/workflows/stackspot.py
